@ProductsAPI_HostAddress = http://localhost:5050

GET {{ProductsAPI_HostAddress}}/weatherforecast/
POST {{ProductsAPI_HostAddress}}/auth/create
GET {{ProductsAPI_HostAddress}}/products
GET {{ProductsAPI_HostAddress}}/products/{id}
Accept: application/json

###
